### PR TITLE
feat: add Nix support via home-manager module

### PR DESCRIPTION
**Pull request by shadeyg56**
Hello, thanks for this awesome theme!

I created a home-manager module for Nix/NixOS users.
I threw this together pretty quickly, so its probably missing some stuff that would be nice, but in terms of just installing the theme it seems to be working

For Nix users, all you have to do is add the repo as a flake input, import the module into home-manager and enable the following settings
```
textfox = {
  enable = true;
  profile = "firefox profile name here"
};
``` 

I couldn't find a way to get the default firefox profile, which is why you have to specify it yourself.
It's also probably possible to install the Sidebery config, but I haven't tried this yet

I haven't updated the README yet with the proper instructions as its getting quite late for me, but I plan to do this so I'll mark this PR as a draft for the time being, but wanted you to be able to go ahead and take a look at it and see if anybody had any improvements that could be made

### CODE REVIEW

**Comment by adriankarlen** [comment]
Thanks, I don't use nix so I can't for sure say anything related to that other than that the installation commands seems to be correct.

I think installing the sidebery config should be manual for now, since it overwrites the config.

**Comment by snaeil** [comment]
I was hoping already for nix home-manager support!
I think it would be great to have a minimal example section in the README file.

How are you doing the import step @shadeyg56 ?

**Comment by shadeyg56** [comment]
> I was hoping already for nix home-manager support!
> 
> I think it would be great to have a minimal example section in the README file.
> 
> 
> 
> How are you doing the import step @shadeyg56 ?


Yeah, planning to add it, I've just been busy today so hopefully I should have some time tonight

**Comment by shadeyg56** [comment]
Sorry for the delay, been busy with school.

I updated the module to automatically install Sidebery (it will not set any settings) and also updated the README to include instructions for Nix.

With that I'm marking this as ready for review.

**Review by adriankarlen — APPROVED** [review]
Looks good, thanks for your contribution!

**Pull request merged**
