### PR TITLE
 urlbar dropdown selector color

### PR DESCRIPTION
**Pull request by himangshusingh**
changed the url bar selector color to a darker shade from the pop pink color, 
added an attribute in userChrome.css to change it to any color suited
texts are more readable now

### CODE REVIEW

**Comment by 909oce** [comment]
you're setting a hardcoded color here, you should probably switch it to use a variable since it will not work with all colorschemes.

**Comment by himangshusingh** [comment]
yeah you are right, I'll make changes to use that

**Comment by adriankarlen** [comment]
As 909oce said I want the css to remain theme agnostic, if you are referring to this it is already set, however I can agree that it is a bit to poppy.
image

**Comment by adriankarlen** [comment]
Closing this as I've resolved this in another PR, thanks for your contribution in ideas and insights.

**Pull request closed without merging**
